/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Wrapped class for Rust native HashMap<String,String>
 * With this structure is possible to allocate millions of entry
 */
export declare class BigMap {
  constructor()
  set(key: string, value: string): void
  get(key: string): string | null
  has(key: string): boolean
  clear(): void
  len(): number
}
